### PR TITLE
Remove Travis test on Nodejs 0.8 and add "stable"

### PR DESCRIPTION
**Pull request by madarche**

### CODE REVIEW

**Comment by dougwilson** [comment]
Sorry, we are not dropping support for Node.js 0.8

**Comment by madarche** [comment]
Sorry :-\ That was because Travis seems to have regular problems with Node.js 0.8.

**Comment by dougwilson** [comment]
I can address it, as it's just Node.js 0.8 + istanbul. The tests fail for this repo because it hasn't been touched in a while and instanbul and it's dependencies use those dumb `^`-style dependencies, breaking things that used to work.

**Comment by dougwilson** [comment]
Ok, tests should pass now with the latest commit.

**Pull request closed without merging**
