### PR TITLE
bump send to 0.19

### PR DESCRIPTION
**Pull request by tommasini**
Bumping send to 0.19 to solve https://github.com/advisories/GHSA-m6fv-jmcg-4jfg

Solves: https://github.com/expressjs/serve-static/issues/175

### CODE REVIEW

**Comment by jayvdb** [comment]
ping @UlisesGascon & @wesleytodd

**Review by IamLizu — APPROVED** [review]
LGTM :heart: :rocket:

**Review by chrysloi — COMMENTED** [review]
LGTM

**Review by UlisesGascon — APPROVED** [review]
LGTM! Thanks @tommasini

**Comment by tommasini** [comment]
@UlisesGascon It's unclear to me why node v8 and v9 unit tests are failing looking at the github CI. Taking a look and running it locally it seems that the 92 tests are passing! Do you have a hint of what's happening?

**Review by leotm — COMMENTED** [review]
Node 8/9 was failing same target branch [`1.x`](https://github.com/expressjs/serve-static/commits/1.x/) similarly couple yrs/days ago

so unrelated to our [bump](https://github.com/pillarjs/send/compare/0.18.0...0.19.0) ^ looks good to merge

**Pull request merged**
